#!/bin/bash
PROMPTS=(
"__happy.png|Middle Eastern corporate negotiator in her 30s-40s, a rare, genuine, bright smile reaching her eyes, looking at the camera, 3/4 take. Deep-set eyes warm and crinkling slightly at the corners, full lips parted in a natural smile. The mole on her left jaw shifting naturally with her expression. Corporate room with glass and cool light behind her. Polished corporate attire, LW Group subtle branding, sport earbud. premium contemporary graphic novel realism, refined editorial line art illustration, waist-up portrait. Clean confident linework, painterly soft shading, muted natural palette, zero conventional beauty templates."
"__vulnerable.png|Middle Eastern corporate negotiator in her 30s-40s, a moment of unguarded exhaustion or doubt, looking slightly away from the camera, 3/4 take. Deep-set eyes softened and weary, arched brows slightly drawn together, full lips resting softly. The stress line between her brows is smoothed out by fatigue. Softened cool light from the crisis center screens. Polished corporate attire, LW Group subtle branding, sport earbud. premium contemporary graphic novel realism, refined editorial line art illustration, waist-up portrait. Clean confident linework, painterly soft shading, muted natural palette, zero conventional beauty templates."
"__tender.png|Middle Eastern corporate negotiator in her 30s-40s, a soft, empathetic expression, looking gently at the camera, 3/4 take. Deep-set eyes warm and understanding, full lips curved in a subtle, comforting way. Her composed bearing slightly relaxed. Corporate negotiation room backdrop. Polished corporate attire, LW Group subtle branding, sport earbud. premium contemporary graphic novel realism, refined editorial line art illustration, waist-up portrait. Clean confident linework, painterly soft shading, muted natural palette, zero conventional beauty templates."
"__sad.png|Middle Eastern corporate negotiator in her 30s-40s, a quiet, contained sorrow, looking slightly down, 3/4 take. Deep-set eyes cast downward, arched brows drawn subtly together, full lips pressed tightly. The faint stress line between her brows is pronounced. Muted cool light in the corporate room. Polished corporate attire, LW Group subtle branding, sport earbud. premium contemporary graphic novel realism, refined editorial line art illustration, waist-up portrait. Clean confident linework, painterly soft shading, muted natural palette, zero conventional beauty templates."
"__shocked.png|Middle Eastern corporate negotiator in her 30s-40s, a sudden break in composure, looking at the camera, 3/4 take. Deep-set eyes wide with disbelief, arched brows raised high, full lips slightly parted. The athletic build stiffens in surprise. Crisis center screens glaring brightly behind her. Polished corporate attire, LW Group subtle branding, sport earbud. premium contemporary graphic novel realism, refined editorial line art illustration, waist-up portrait. Clean confident linework, painterly soft shading, muted natural palette, zero conventional beauty templates."
"__angry.png|Middle Eastern corporate negotiator in her 30s-40s, a cold, sharp fury, looking intensely at the camera, 3/4 take. Deep-set eyes narrowed into a piercing glare, arched brows drawn sharply down, full lips pulled into a tight, hard line. The faint stress line between her brows deepens dramatically. Harsher cool light hitting her clear olive skin. Polished corporate attire, LW Group subtle branding, sport earbud. premium contemporary graphic novel realism, refined editorial line art illustration, waist-up portrait. Clean confident linework, painterly soft shading, muted natural palette, zero conventional beauty templates."
"__surprised.png|Middle Eastern corporate negotiator in her 30s-40s, a mild, controlled startle, looking at the camera, 3/4 take. Deep-set eyes slightly widened, arched brows lifted moderately, lips in a neutral but attentive position. Her composed bearing re-asserting itself. Corporate negotiation room backdrop. Polished corporate attire, LW Group subtle branding, sport earbud. premium contemporary graphic novel realism, refined editorial line art illustration, waist-up portrait. Clean confident linework, painterly soft shading, muted natural palette, zero conventional beauty templates."
)

for p in "${PROMPTS[@]}"; do
    FILENAME=$(echo "$p" | cut -d'|' -f1)
    PROMPT_TEXT=$(echo "$p" | cut -d'|' -f2)
    ENCODED=$(jq -nr --arg v "$PROMPT_TEXT" '$v|@uri')
    URL="https://image.pollinations.ai/prompt/${ENCODED}?model=flux&width=768&height=1024"
    echo "Downloading $FILENAME..."
    curl -sL "$URL" -o "content/characters/nadia_al_farsi/assets/nadia_al_farsi${FILENAME}"
    sleep 1
done
