// api/contracts/src/revision/revision-pointer.ts
// Revision pointer format, read interface, atomic flip semantics.
// Planning writes, runtime reads — runtime cannot write.

import type { ArtifactId } from '../artifact/artifact.js';

/**
 * Unique identifier for a revision.
 * UUID v4 format for maximum compatibility.
 */
export type RevisionId = string;

/**
 * Timestamp in ISO 8601 format (UTC).
 */
export type ISODateString = string;

/**
 * A revision pointer identifies a specific revision of content.
 * 
 * Key semantics:
 * - planning module WRITES revision pointers (creates new revisions)
 * - runtime module READS revision pointers (consumes active revisions)
 * - runtime CANNOT write revision pointers (architectural boundary)
 * - atomic flip: switching from one revision to another is atomic
 *   (no intermediate state where partial revision is visible)
 */
export interface RevisionPointer {
  /**
   * Unique identifier for this revision.
   * Generated by planning when a new revision is created.
   */
  revisionId: RevisionId;

  /**
   * The type of entity this revision versions (e.g. 'scene', 'dialogue', 'mission').
   *
   * Required rather than optional: RevisionPointerReader scopes every read by
   * (entityType, entitySlug), so a pointer without that identity cannot be found
   * again, cannot be deactivated on flip, and cannot enforce the one-active-
   * revision-per-entity invariant.
   */
  entityType: string;

  /**
   * The slug of the entity this revision versions (e.g. 'great_lithium_leak').
   * Required for the same reason as `entityType`.
   */
  entitySlug: string;

  /**
   * Whether this revision is currently active/visible to runtime.
   * Only one revision per entity can be active at a time.
   */
  active: boolean;

  /**
   * Timestamp when this revision was created.
   */
  createdAt: ISODateString;

  /**
   * The artifact ID that this revision points to.
   * This is the content-addressed reference to the actual content.
   */
  artifactId: ArtifactId;

  /**
   * Optional description of what changed in this revision.
   */
  description?: string;

  /**
   * Optional metadata about this revision.
   * Can include author, source, etc.
   */
  metadata?: Record<string, unknown>;
}

/**
 * Minimal revision pointer for read operations.
 * Runtime only needs to read: revisionId, active, createdAt, artifactId.
 */
export interface RevisionPointerRead {
  revisionId: RevisionId;
  active: boolean;
  createdAt: ISODateString;
  artifactId: ArtifactId;
}

/**
 * Input for creating a new revision pointer.
 * Used by planning module when compiling/publishing new content.
 */
export interface RevisionPointerCreate {
  /**
   * The type of entity this revision versions. Required so a created pointer can
   * be associated with the entity it versions — without it the writer cannot
   * scope reads by (entityType, entitySlug) or enforce one active revision per
   * entity, even though the reader interface requires both.
   */
  entityType: string;

  /**
   * The slug of the entity this revision versions. Required for the same reason
   * as `entityType`.
   */
  entitySlug: string;

  artifactId: ArtifactId;
  description?: string;
  metadata?: Record<string, unknown>;
}

/**
 * Result of creating a new revision pointer.
 * Includes the generated revisionId and timestamp.
 */
export interface RevisionPointerCreated {
  revisionPointer: RevisionPointer;
}

/**
 * Atomic flip operation: activate a new revision, deactivate the old one.
 * This is the interface that planning uses to publish new content.
 * 
 * Semantics:
 * - The flip is atomic: either both activate/deactivate succeed, or neither does
 * - Only ONE revision per entity can be active at a time
 * - The old active revision is deactivated (active = false)
 * - The new revision is activated (active = true)
 */
export interface AtomicFlip {
  /**
   * The revision to activate.
   * Must exist and currently be inactive.
   */
  newRevisionId: RevisionId;

  /**
   * The revision to deactivate.
   * Must exist and currently be active.
   * Can be omitted if this is the first revision for an entity.
   */
  oldRevisionId?: RevisionId;

  /**
   * Optional: the entity type this revision belongs to.
   * e.g., 'scene', 'dialogue', 'mission'
   */
  entityType?: string;

  /**
   * Optional: the entity slug this revision belongs to.
   * e.g., 'great_lithium_leak'
   */
  entitySlug?: string;
}

/**
 * Result of an atomic flip operation.
 */
export interface AtomicFlipResult {
  /**
   * Whether the flip succeeded.
   */
  success: boolean;

  /**
   * The new active revision (if successful).
   */
  newActiveRevision?: RevisionPointerRead;

  /**
   * The old active revision that was deactivated (if any).
   */
  oldActiveRevision?: RevisionPointerRead;

  /**
   * Error message if the flip failed.
   */
  error?: string;
}

/**
 * Read interface for revision pointers.
 * This is what runtime uses to access revision information.
 * 
 * Key constraint: runtime CANNOT write through this interface.
 * All methods are read-only.
 */
export interface RevisionPointerReader {
  /**
   * Get the currently active revision for an entity.
   * Returns undefined if no active revision exists.
   */
  getActiveRevision(
    entityType: string,
    entitySlug: string,
  ): Promise<RevisionPointerRead | undefined>;

  /**
   * Get a specific revision by ID.
   * Can return inactive revisions for historical access.
   */
  getRevision(revisionId: RevisionId): Promise<RevisionPointerRead | undefined>;

  /**
   * List all revisions for an entity, ordered by createdAt descending.
   */
  listRevisions(
    entityType: string,
    entitySlug: string,
  ): Promise<RevisionPointerRead[]>;

  /**
   * List all active revisions (one per entity).
   */
  listActiveRevisions(): Promise<RevisionPointerRead[]>;
}

/**
 * Write interface for revision pointers.
 * This is what planning uses to create and manage revisions.
 * 
 * Runtime CANNOT and SHOULD NOT have access to this interface.
 */
export interface RevisionPointerWriter {
  /**
   * Create a new revision pointer.
   * The new revision starts as inactive.
   */
  createRevision(
    input: RevisionPointerCreate,
  ): Promise<RevisionPointerCreated>;

  /**
   * Perform an atomic flip to activate a new revision.
   */
  atomicFlip(input: AtomicFlip): Promise<AtomicFlipResult>;

  /**
   * Retire a revision (mark it as no longer available).
   * Cannot retire the currently active revision.
   * This is a soft delete - the revision is kept for history.
   */
  retireRevision(revisionId: RevisionId): Promise<boolean>;
}

/**
 * Combined read+write interface for revision pointers.
 * Only planning should have access to this.
 */
export interface RevisionPointerRepository
  extends RevisionPointerReader,
    RevisionPointerWriter {}

/**
 * Type guard for RevisionPointer.
 *
 * Validates the optional `description` / `metadata` fields when present: without
 * those checks the predicate would narrow a non-string description or a
 * non-plain-object metadata (an array, `null`, a number) to the declared
 * `RevisionPointer` shape.
 */
export function isRevisionPointer(value: unknown): value is RevisionPointer {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    return false;
  }
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.revisionId === 'string' &&
    typeof obj.entityType === 'string' &&
    typeof obj.entitySlug === 'string' &&
    typeof obj.active === 'boolean' &&
    typeof obj.createdAt === 'string' &&
    typeof obj.artifactId === 'string' &&
    (obj.description === undefined || typeof obj.description === 'string') &&
    (obj.metadata === undefined ||
      (typeof obj.metadata === 'object' && obj.metadata !== null && !Array.isArray(obj.metadata)))
  );
}

/**
 * Type guard for RevisionPointerRead.
 */
export function isRevisionPointerRead(
  value: unknown,
): value is RevisionPointerRead {
  if (typeof value !== 'object' || value === null) {
    return false;
  }
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.revisionId === 'string' &&
    typeof obj.active === 'boolean' &&
    typeof obj.createdAt === 'string' &&
    typeof obj.artifactId === 'string'
  );
}

/**
 * Creates a revision pointer from its components.
 */
export function createRevisionPointer(
  input: Omit<RevisionPointer, 'revisionId' | 'createdAt'> & {
    revisionId: RevisionId;
    createdAt: ISODateString;
  },
): RevisionPointer {
  return {
    revisionId: input.revisionId,
    entityType: input.entityType,
    entitySlug: input.entitySlug,
    active: input.active,
    createdAt: input.createdAt,
    artifactId: input.artifactId,
    description: input.description,
    metadata: input.metadata,
  };
}
