import type { ContentType, AssetNeed } from '@las-flores/shared';

type AssetNeedStatus = AssetNeed['status'];

/**
 * Valid state transitions for asset needs.
 * Each key maps to the list of states that can follow it.
 */
const VALID_TRANSITIONS: Record<AssetNeedStatus, AssetNeedStatus[]> = {
  pending: ['drafted', 'chosen', 'failed'],
  drafted: ['chosen', 'failed', 'pending'],
  chosen: ['published', 'failed', 'drafted'],
  published: ['assigned', 'failed'],
  assigned: ['failed'],
  failed: ['pending'],
};

/**
 * Transition an asset need to a new status.
 * Throws if the transition is invalid.
 */
export function transitionAssetNeed(need: AssetNeed, next: AssetNeedStatus): void {
  if (!VALID_TRANSITIONS[need.status]?.includes(next)) {
    throw new Error(`Invalid asset need transition: ${need.status} → ${next}`);
  }
  need.status = next;
}

/**
 * Static asset needs per content type.
 * Maps to the asset_paths generated by ContentSkeletonGenerator.
 * Only types with visual assets are included.
 */
const ASSET_NEEDS: Partial<Record<ContentType, AssetNeed[]>> = {
  character: [
    { promptType: 'portrait', targetField: 'asset_paths.portrait', status: 'pending' },
    { promptType: 'biometric', targetField: 'asset_paths.biometric', status: 'pending' },
  ],
  scene: [
    { promptType: 'background', targetField: 'asset_paths.background', status: 'pending' },
  ],
  location: [
    { promptType: 'image', targetField: 'asset_paths.image', status: 'pending' },
    { promptType: 'background', targetField: 'asset_paths.background', status: 'pending' },
  ],
  overlay: [
    { promptType: 'background', targetField: 'asset_paths.background', status: 'pending' },
  ],
};

/**
 * Inject asset needs into plan items that don't already have them.
 * Called after LLM generates or refines a plan.
 */
export function injectAssetNeeds(items: Array<{ type: ContentType; assetNeeds: AssetNeed[] }>): void {
  for (const item of items) {
    if (item.assetNeeds.length === 0 && ASSET_NEEDS[item.type]) {
      item.assetNeeds = ASSET_NEEDS[item.type]!.map(need => ({ ...need }));
    }
  }
}
