import fs from 'node:fs/promises';
import path from 'node:path';
import yaml from 'js-yaml';
import type { ContentPlan, ContentPlanItem } from '@las-flores/shared';
import { uploadToMinio } from './StorageService.js';
import { markPublished } from './AssetNeedsService.js';
import { resolveEntityRootDir } from './LocalDraftService.js';
import { resolveFilePath } from './ContentSkeletonGenerator.js';
import { queryOLTP } from '../database/connection.js';

export interface PublishedAsset {
  itemId: string;
  itemType: string;
  needId: string;
  localFilename: string;
  url: string;
  objectKey: string;
}

export interface PublishResult {
  success: boolean;
  published: PublishedAsset[];
  errors: string[];
}

function resolveContentDir(): string {
  return path.resolve(process.cwd(), 'content');
}

/**
 * Fallback local filename when the user never visited the asset panel and
 * no `asset_paths.<field>` is recorded. The historical default
 * `<slug>__default.png` is auto-generated by stagePlan()'s templates, so it
 * is the safest draft to publish.
 */
function defaultLocalFilename(item: ContentPlanItem): string {
  return `${item.slug}__default.png`;
}

/**
 * "Publish the chosen draft" per asset need for an APPROVED plan.
 *
 * For every `AssetNeed` with `status='chosen'` (or, via fallback, the
 * `<slug>__default.png` historical default):
 *   1. Read the local bytes from the per-entity `assets/<filename>` folder.
 *   2. Upload to MinIO at `<assetType>/<filename>` — the local filename is
 *      preserved as the object key (no `.dev` suffix).
 *   3. Append a `label: 'dev'` entry to the YAML's `portrait_urls` JSONB
 *      array. The cascade lives in the YAML (and is carried into the DB by
 *      the subsequent migration), NOT in the object key.
 *   4. Mark `AssetNeed.status='published'`.
 *
 * Note: the YAML's `asset_paths.<field>` is deliberately left pointing at the
 * LOCAL filename — it is the source of truth for the author, while MinIO is
 * the delivery layer for the engine.
 */
export async function publishChosenDrafts(planId: string): Promise<PublishResult> {
  const load = await queryOLTP<{ plan_json: any }>(
    'SELECT plan_json FROM content_plans WHERE id = $1',
    [planId],
  );
  if (load.rows.length === 0) {
    throw new Error(`Plan not found: ${planId}`);
  }

  const plan = load.rows[0].plan_json as ContentPlan;
  const contentDir = resolveContentDir();

  const published: PublishedAsset[] = [];
  const errors: string[] = [];

  for (const item of plan.items) {
    const entityRoot = resolveEntityRootDir(item, contentDir);
    const yamlPath = path.join(contentDir, resolveFilePath(item));

    // stagePlan() wrote this YAML. Read it so we can append the dev entry
    // without clobbering anything the templates generated.
    let yamlData: Record<string, any> = {};
    try {
      const raw = await fs.readFile(yamlPath, 'utf-8');
      yamlData = (yaml.load(raw) as Record<string, any>) || {};
    } catch (err: any) {
      errors.push(`${item.name}: could not read staged YAML at ${yamlPath}: ${err.message}`);
      continue;
    }

    const assetPaths = (item.fields as any)?.asset_paths || {};
    const chosenNeeds = item.assetNeeds.filter(n => n.status === 'chosen' || n.status === 'pending');
    if (chosenNeeds.length === 0) continue;

    const uploadedNeeds: Array<{
      need: ContentPlanItem['assetNeeds'][number];
      localFilename: string;
      url: string;
      objectKey: string;
    }> = [];

    for (const need of chosenNeeds) {
      const localFilename = assetPaths[need.promptType] || defaultLocalFilename(item);
      const localPath = path.resolve(entityRoot, 'assets', localFilename);
      const assetsRoot = path.resolve(entityRoot, 'assets');
      if (localPath !== assetsRoot && !localPath.startsWith(assetsRoot + path.sep)) {
        errors.push(`${item.name} / ${need.promptType}: local path escapes assets directory: ${localFilename}`);
        continue;
      }
      try {
        const buf = await fs.readFile(localPath);
        // The MinIO object key preserves the local filename. The bucket is
        // `las-flores`, so the object location is `las-flores/<assetType>/<filename>`.
        const objectKey = `${need.promptType}/${localFilename}`;
        const url = await uploadToMinio(buf, objectKey, 'image/png');

        // Record the published URL in the YAML.
        // For characters, append to the portrait_urls cascade array.
        // For other types, write directly to the target field (e.g. image_url).
        // portrait_urls entries are deduplicated by url+label to avoid
        // duplicate dev entries on retry.
        if (need.targetField.startsWith('portrait_urls')) {
          const portraitUrls: Array<{ url: string; label?: string }> = Array.isArray(
            yamlData.portrait_urls,
          )
            ? (yamlData.portrait_urls as Array<{ url: string; label?: string }>)
            : [];
          if (!portraitUrls.some(p => p.url === url && p.label === 'dev')) {
            portraitUrls.push({ url, label: 'dev' });
          }
          yamlData.portrait_urls = portraitUrls;
        } else {
          yamlData[need.targetField] = url;
        }

        uploadedNeeds.push({ need, localFilename, url, objectKey });
      } catch (err: any) {
        errors.push(`${item.name} / ${need.promptType}: ${err.message}`);
      }
    }

    // Only write the YAML if at least one upload succeeded for this item.
    if (uploadedNeeds.length > 0) {
      try {
        await fs.writeFile(yamlPath, yaml.dump(yamlData, { lineWidth: -1, noRefs: true }), 'utf-8');
        for (const { need, localFilename, url, objectKey } of uploadedNeeds) {
          markPublished(need);
          published.push({
            itemId: item.id,
            itemType: item.type,
            needId: need.promptType,
            localFilename,
            url,
            objectKey,
          });
        }
      } catch (err: any) {
        errors.push(`${item.name}: failed to write portrait_urls to YAML: ${err.message}`);
      }
    }
  }

  // Persist the updated asset-need statuses back into plan_json (audit trail).
  await queryOLTP('UPDATE content_plans SET plan_json = $1, updated_at = NOW() WHERE id = $2', [
    plan,
    planId,
  ]);

  return { success: errors.length === 0, published, errors };
}
