import type { ContentType, AssetNeed } from '@las-flores/shared';

/**
 * Static asset needs per content type.
 * Maps to the asset_paths generated by ContentSkeletonGenerator.
 * Only types with visual assets are included.
 */
const ASSET_NEEDS: Partial<Record<ContentType, AssetNeed[]>> = {
  character: [
    { promptType: 'portrait', targetField: 'asset_paths.portrait', status: 'pending' },
    { promptType: 'biometric', targetField: 'asset_paths.biometric', status: 'pending' },
  ],
  scene: [
    { promptType: 'background', targetField: 'asset_paths.background', status: 'pending' },
  ],
  location: [
    { promptType: 'image', targetField: 'asset_paths.image', status: 'pending' },
    { promptType: 'background', targetField: 'asset_paths.background', status: 'pending' },
  ],
  overlay: [
    { promptType: 'background', targetField: 'asset_paths.background', status: 'pending' },
  ],
};

/**
 * Inject asset needs into plan items that don't already have them.
 * Called after LLM generates or refines a plan.
 */
export function injectAssetNeeds(items: Array<{ type: ContentType; assetNeeds: AssetNeed[] }>): void {
  for (const item of items) {
    if (item.assetNeeds.length === 0 && ASSET_NEEDS[item.type]) {
      item.assetNeeds = ASSET_NEEDS[item.type]!.map(need => ({ ...need }));
    }
  }
}
