/**
 * Integration test — M24 claims/evidence store lifecycle (real DB).
 *
 * Verifies: propose → record review evidence → accept → merged (with
 * conflict reason), the append-only transition journal, and claim detail
 * mapping. Uses dedicated synthetic UUIDs and cleans up in afterAll.
 */
import { describe, test, expect, beforeAll, afterAll } from '@jest/globals';
import fs from 'fs';
import path from 'path';
import pg from 'pg';
import { withSchemaLock } from '../helpers/schemaLock.js';
import {
  createClaim,
  transitionClaim,
  recordEvidence,
  getClaimDetail,
  rejectClaimsForPatch,
} from '../../src/services/ClaimsService.js';
import { queryOLTP } from '@las-flores/infra';
import { ClaimTransitionError } from '../../src/services/errors.js';

const { Pool } = pg;

// Fixture IDs are generated by the DB (gen_random_uuid) and collected here, so
// no other test can touch them (collision-avoidance per AGENTS.md). Cleaned up
// in afterAll.
const CLAIM_IDS: string[] = [];
const PATCH_IDS: string[] = [];

let pool: pg.Pool;

async function applyMigration(filename: string): Promise<void> {
  const sql = fs.readFileSync(
    path.resolve(process.cwd(), 'src/database/migrations', filename),
    'utf-8',
  );
  await withSchemaLock(async (client) => {
    await client.query(sql);
  });
}

describe('claims-lifecycle', () => {
  beforeAll(async () => {
    pool = new Pool({
      connectionString:
        process.env.DATABASE_URL || 'postgresql://las_flores:las_flores_dev_password@localhost:5434/las_flores',
      connectionTimeoutMillis: 5000,
    });
    await applyMigration('064_patch_versioning.sql');
    await applyMigration('066_claims.sql');
    await applyMigration('067_admin_events_audit.sql');
    await applyMigration('068_admin_events_audit_validate.sql');
  });

  afterAll(async () => {
    if (CLAIM_IDS.length || PATCH_IDS.length) {
      // The evidence / claim_transitions immutability triggers block direct
      // DELETE/TRUNCATE by default. Bypass requires BOTH the GUC
      // (`claim_utils.allow_mutation = 'true'`) AND privilege (superuser OR
      // `las_flores_claims_retention` role). The dev/test connection role is
      // typically the bootstrap superuser, which already satisfies
      // mutation_allowed(), so no GRANT is needed here. We deliberately do NOT
      // GRANT the retention role: doing so inside this transaction would COMMIT
      // the membership into pg_auth_members permanently, persistently handing the
      // app login role the audit-bypass privilege and weakening the immutability
      // gate outside the test. Set only the session-local GUC within an explicit
      // transaction for fixture cleanup. node-postgres disallows parameters across
      // multiple statements in a single pooled query, so drive the transaction
      // through a client and issue each statement separately.
      const client = await pool.connect();
      try {
        await client.query('BEGIN');
        await client.query(`SET LOCAL claim_utils.allow_mutation = 'true'`);
        if (CLAIM_IDS.length) {
          await client.query(
            `DELETE FROM claim_transitions WHERE claim_id = ANY($1::uuid[])`,
            [CLAIM_IDS],
          );
          await client.query(
            `DELETE FROM evidence WHERE claim_id = ANY($1::uuid[])`,
            [CLAIM_IDS],
          );
          await client.query(
            `DELETE FROM claims WHERE id = ANY($1::uuid[])`,
            [CLAIM_IDS],
          );
        }
        if (PATCH_IDS.length) {
          await client.query(
            `DELETE FROM patches WHERE id = ANY($1::uuid[])`,
            [PATCH_IDS],
          );
        }
        await client.query('COMMIT');
      } catch (err) {
        await client.query('ROLLBACK');
        throw err;
      } finally {
        client.release();
      }
    }
    await pool.end();
  });

  test('runs proposal → accepted → merged with evidence + journal', async () => {
    const id = await createClaim(
      {
        claimText: 'Hansel keeps the keys to the dead drop',
        sourceSpan: 'Chapter 14, para 3',
        sourceRef: 'character:hansel',
        confidence: 0.72,
      },
      undefined,
    );
    CLAIM_IDS.push(id);

    // Append evidence.
    await recordEvidence(id, { sourceSpan: 'Chapter 14, para 3', evidenceText: 'He slides the ring east of the pump house.' }, undefined);

    // Accept.
    const accepted = await transitionClaim(id, 'accepted', undefined, undefined);
    expect(accepted.status).toBe('accepted');

    // Merge.
    const merged = await transitionClaim(id, 'merged', 'aligned with scene estate_house', undefined);
    expect(merged.status).toBe('merged');

    // Invalid edge from merged.
    await expect(transitionClaim(id, 'accepted', 'x', undefined)).rejects.toBeInstanceOf(ClaimTransitionError);

    const detail = await getClaimDetail(id);
    expect(detail.claim.status).toBe('merged');
    expect(detail.claim.confidence).toBe(0.72);
    expect(detail.evidence).toHaveLength(1);
    expect(detail.evidence[0].evidenceText).toContain('pump house');
    // Journal: initial (null→proposed), accepted, merged.
    expect(detail.transitions.length).toBeGreaterThanOrEqual(3);
  });

  test('rejectClaimsForPatch rejects a patch\u2019s claimed proposal', async () => {
    // Create a real patch row so the claims.patch_id FK is satisfied.
    const patchRes = await queryOLTP<{ id: string }>(
      `INSERT INTO patches (title, status) VALUES ('claimable patch', 'proposed') RETURNING id`,
      [],
    );
    const patchId = patchRes.rows[0].id;
    PATCH_IDS.push(patchId);
    const id = await createClaim(
      { claimText: 'Proposed claim tied to a patch', patchId, confidence: 0.5 },
      undefined,
    );
    CLAIM_IDS.push(id);

    const count = await rejectClaimsForPatch(patchId, 'out of scope', undefined);
    expect(count).toBeGreaterThanOrEqual(1);

    const detail = await getClaimDetail(id);
    expect(detail.claim.status).toBe('rejected');
    expect(detail.claim.conflictReason).toBe('out of scope');
  });
});